# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

shopt -s nocaseglob

alias l='ls -alF'
alias ll='ls -l'
alias la='ls -alF'

alias start-cluster='cd /home/limingyao/.local/hadoop && ./sbin/start-dfs.sh && ./sbin/start-yarn.sh && ./sbin/yarn-daemon.sh start proxyserver && ./sbin/mr-jobhistory-daemon.sh start historyserver'
alias stop-cluster='cd /home/limingyao/.local/hadoop && ./sbin/stop-yarn.sh && ./sbin/mr-jobhistory-daemon.sh stop historyserver && ./sbin/stop-dfs.sh'

